# Generated by Django 5.2.5 on 2025-10-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_managers_alter_usuario_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Para técnicos: área de especialización', max_length=100, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='max_tickets_simultaneos',
            field=models.PositiveIntegerField(default=10, help_text='Límite de tickets activos que puede manejar', verbose_name='Máximo tickets simultáneos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='recibir_notificaciones',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones por email'),
        ),
    ]
