# Generated by Django 5.2.5 on 2025-09-07 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.UUIDField()),
                ('tipo', models.CharField(choices=[('creacion', 'Creación de Ticket'), ('asignacion', 'Asignación de Agente'), ('cambio_estado', 'Cambio de Estado'), ('comentario', 'Nuevo Comentario'), ('adjunto', 'Archivo Adjuntado'), ('cierre', 'Cierre de Ticket'), ('reapertura', 'Reapertura de Ticket')], max_length=20)),
                ('descripcion', models.TextField()),
                ('datos_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_id', 'created_at'], name='audit_event_ticket__6e9de5_idx'), models.Index(fields=['tipo'], name='audit_event_tipo_1f2ac6_idx')],
            },
        ),
    ]
