# Generated by Django 5.2.5 on 2025-09-07 02:43

import attachments.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objeto_id', models.UUIDField()),
                ('tipo_objeto', models.CharField(choices=[('ticket', 'Ticket'), ('comentario', 'Comentario')], max_length=10)),
                ('archivo', models.FileField(upload_to=attachments.models.upload_to_ticket, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'pdf'])])),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento')], max_length=10)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamaño_bytes', models.PositiveIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['objeto_id', 'tipo_objeto'], name='attachments_objeto__c0e2ad_idx')],
            },
        ),
    ]
