# Generated by Django 5.2.5 on 2025-10-03 00:05

import attachments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoMultiple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, verbose_name='Clave de Sesión')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Adjunto Múltiple',
                'verbose_name_plural': 'Adjuntos Múltiples',
                'ordering': ['orden', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='adjunto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Adjunto', 'verbose_name_plural': 'Adjuntos'},
        ),
        migrations.AddField(
            model_name='adjunto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='es_publico',
            field=models.BooleanField(default=True, verbose_name='Es Público'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='archivo',
            field=models.FileField(upload_to=attachments.models.upload_to_ticket, validators=[attachments.models.validar_extension_archivo], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Checksum SHA-256'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='nombre_original',
            field=models.CharField(max_length=255, verbose_name='Nombre Original'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='objeto_id',
            field=models.UUIDField(verbose_name='ID del Objeto'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='tamaño_bytes',
            field=models.PositiveIntegerField(verbose_name='Tamaño en Bytes'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='tipo_archivo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Archivo'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='tipo_mime',
            field=models.CharField(max_length=100, verbose_name='Tipo MIME'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='tipo_objeto',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('comentario', 'Comentario')], max_length=20, verbose_name='Tipo de Objeto'),
        ),
        migrations.AddIndex(
            model_name='adjunto',
            index=models.Index(fields=['tipo_archivo'], name='attachments_tipo_ar_1f41e5_idx'),
        ),
        migrations.AddIndex(
            model_name='adjunto',
            index=models.Index(fields=['subido_por'], name='attachments_subido__7210c2_idx'),
        ),
        migrations.AddIndex(
            model_name='adjunto',
            index=models.Index(fields=['created_at'], name='attachments_created_688683_idx'),
        ),
        migrations.AddField(
            model_name='adjuntomultiple',
            name='adjunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.adjunto', verbose_name='Adjunto'),
        ),
    ]
