# Generated by Django 5.2.5 on 2025-10-03 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comentario',
            name='tickets_com_ticket__c2a0c7_idx',
        ),
        migrations.AddField(
            model_name='categoria',
            name='dias_garantia_defecto',
            field=models.PositiveIntegerField(default=365, verbose_name='Días de garantía por defecto'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='requiere_factura',
            field=models.BooleanField(default=True, verbose_name='Requiere factura'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='requiere_numero_serie',
            field=models.BooleanField(default=True, verbose_name='Requiere número de serie'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='es_respuesta_inicial',
            field=models.BooleanField(default=False, verbose_name='Es respuesta inicial'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='resuelve_ticket',
            field=models.BooleanField(default=False, verbose_name='Resuelve el ticket'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_primera_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Primera Respuesta'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_vencimiento_garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento Garantía'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='garantia_vigente',
            field=models.BooleanField(default=False, verbose_name='Garantía Vigente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tecnico',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'soporte_tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_tecnicos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tiempo_resolucion_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de Resolución (horas)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tiempo_respuesta_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de Respuesta (horas)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_reclamo',
            field=models.CharField(choices=[('garantia', 'Garantía'), ('reclamo', 'Reclamo'), ('consulta', 'Consulta'), ('devolucion', 'Devolución')], default='reclamo', max_length=20, verbose_name='Tipo de Reclamo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='visibilidad',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10, verbose_name='Visibilidad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='agente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['soporte', 'empleado']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Agente Asignado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asunto',
            field=models.CharField(max_length=200, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tickets.categoria', verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del Problema'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En Revisión'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('en_reparacion', 'En Reparación'), ('en_espera_cliente', 'En Espera del Cliente'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero_factura',
            field=models.CharField(max_length=50, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['ticket'], name='tickets_com_ticket__4217df_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['autor'], name='tickets_com_autor_i_86f0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['created_at'], name='tickets_com_created_c881c3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridad'], name='tickets_tic_priorid_554483_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tecnico'], name='tickets_tic_tecnico_8871b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['numero_serie'], name='tickets_tic_numero__93cb21_idx'),
        ),
    ]
